### ISSUE TITLE
Export JIRA Backlog into GitHub Project

### ISSUE THREAD

**Issue by SensehacK** [SensehacK/health-sense#10]
Please populate everything!

- [x]  Add Labels
- [x] JIRA Sprints
- [x] JIRA Backlogs
- [x] Documentation
- [x] Two sprint planning
- [x]  Milestone
- [x] Peer review

**Comment by rtrend96** [comment]
@endri969 need help

**Comment by SensehacK** [comment]
Any update with next 2 weeks plan of action @rtrend96 Agile coach.

**Comment by rtrend96** [comment]
@SensehacK sprint planning is remaining.

**Comment by rtrend96** [comment]
Done with all sprint backlog
