### ISSUE TITLE
Information Gathering

### ISSUE THREAD

**Issue by rtrend96** [SensehacK/health-sense#12]
Gather all information for the project to complete idea

Task list
- [x] Requirement Gathering
- [x] Design
- [x] Development
- [x] Testing

**Comment by SensehacK** [comment]
@rtrend96 Please go through the Research Paper, I have listed out all of the required information gathering stuff for iOS #3 

Android information maybe @endri969 @Abbas-shamshi can pitch in with the functional requirements.
