### ISSUE TITLE
Android Requirement 

### ISSUE THREAD

**Issue by rtrend96** [SensehacK/health-sense#13]
Put android requirements in paper or upload in google drive.

**Comment by endri969** [comment]
For Android
Accelerometer sensor access
Bluetooth access for smart watch access
Read/Write access to Android wear API
Authenticate with touch or face Google API
For Notifications, Notification access would be necessary
@rtrend96

**Comment by rtrend96** [comment]
thank you @endri969

**Comment by rtrend96** [comment]
@endri969 Looks good i am submmiting it.
