### ISSUE TITLE
Feedback on other technical Papers

### ISSUE THREAD

**Issue by rtrend96** [SensehacK/health-sense#22]
All the technical papers are on the Pace Portal.
We have to give feedback about each paper for the next team feedback.
So go through each technical paper and send your feedback in the WhatsApp group.

**Comment by rtrend96** [comment]
@SensehacK @endri969 @Abbas-shamshi @ManasiTayade we will divide each paper for feedback. 
Please Select the paper for feedback.

**Comment by Abbas-shamshi** [comment]
Going through Pace Market place Technical paper

**Comment by rtrend96** [comment]
Guys please send me feedback ASAP 
@endri969 @rtrend96 @Abbas-shamshi @ManasiTayade

**Comment by rtrend96** [comment]
done with all feedback
