### ISSUE TITLE
Technical Paper

### ISSUE THREAD

**Issue by SensehacK** [SensehacK/health-sense#3]
Technical paper work 

Manasi & rushi 

- [x] Abstract 
- [x] Introduction 
- [x] Literature survey 

Abbas  and endri 

- [x] Database schema
- [x] Data modeling 

Kautilya
- [x] Project requirements 
- [x] System diagram 

Rushi 

- [x] Conclusion and discussion 
- [x] Summary 
- [x] Give me all reference 
- [x] Reference

submission is on wednesday

**Comment by ManasiTayade** [comment]
Got it

**Comment by ManasiTayade** [comment]
Guys if you are done with the data please send in the group or doc file so I can start with the abstract and introduction part. @endri969 @Abbas-shamshi @SensehacK #3

**Comment by SensehacK** [comment]
@ManasiTayade Done with my part. Please share me the Gdrive folder @rtrend96  so that we can privately share those WIP documents.

**Comment by ManasiTayade** [comment]
Abstract and a part of introduction done and uploaded on drive please review. Also project description is posted on docs please review that as well and make necessary changes if required.

**Comment by rtrend96** [comment]
@endri969 reveiw on the data modeling and data scheme

**Comment by rtrend96** [comment]
@ManasiTayade please uplaod Literature survey.

**Comment by ManasiTayade** [comment]
> @ManasiTayade please uplaod Literature survey.

yes

**Comment by rtrend96** [comment]
@Abbas-shamshi @SensehacK @endri969 can you guys explain your diagrams in  2 3 lines.

**Comment by ManasiTayade** [comment]
@rtrend96 done with my part.

**Comment by rtrend96** [comment]
We have done with all tasks now I am closing the issue.
