### ISSUE TITLE
Onboading Welcome Screen Design 

### ISSUE THREAD

**Issue by rtrend96** [SensehacK/health-sense#33]
The functionality of adding a feature for iOS application which would add-in
- [x] Logo Design 
- [x] Launch Screen Design
- [x] Start Screen Design

### Dependency
1. Sketch

### Link to refer

- [ ] [Link 1](https://icons8.com/articles/ux-design-onboarding-mobile-app/)

- [ ] [Link 2](https://growth.design/case-studies/5-product-onboarding-mistakes-to-avoid/)

**Comment by SensehacK** [comment]
Please add other links which I have shared to you about good onboarding UX. @rtrend96 

@ManasiTayade hope these links would suffice for designing good onboarding UX.
