### ISSUE TITLE
Database Design

### ISSUE THREAD

**Issue by SensehacK** [SensehacK/health-sense#4]

**Comment by rtrend96** [comment]
@endri969 please review it.

**Comment by endri969** [comment]
![image](https://user-images.githubusercontent.com/24678923/79408302-03c8b400-7f69-11ea-91fd-27c8ab20653f.png)

I changed a little bit the the Database desing

**Comment by endri969** [comment]
Link for the SQL schema
[https://drive.google.com/open?id=1cj423E0kQpJf59BuEfvmnenvoPRLHs3t](url)

**Comment by SensehacK** [comment]
@Abbas-shamshi is there any conflict with the database design?

If everything looks good, then you or endri can close this TODO.
Could be added to Milestone v3.

**Comment by rtrend96** [comment]
done with database creation task.
