### ISSUE TITLE
Summary screen shows no data on launch

### ISSUE THREAD

**Issue by ManasiTayade** [SensehacK/health-sense#47]
## Bug Report

**Current Behavior**
Once you open the application the summary screen displays no data on first launch.

**Expected behavior/code**
The saved data should appear every time you launch the application. 

**Environment**

- Xcode version(s): 11.4.1
- iPhone : 13.4.1
- OS: MacOS 10.15.3
- How you are using App build: Xcode run

**Possible Solution**

**Note: for support questions, please use stackoverflow**. This repository's issues are reserved for feature requests and bug reports.

**Additional context/Screenshots**
<img width="495" alt="Screen Shot 2020-05-04 at 3 21 22 PM" src="https://user-images.githubusercontent.com/58129928/81004837-00fc0900-8e1b-11ea-9674-1c84bb068725.png">

**Comment by SensehacK** [comment]
This is also closed in latest PR! @ManasiTayade  please test & let us know if its still reproducible.
