### ISSUE TITLE
Dark Mode Inconsistency 

### ISSUE THREAD

**Issue by ManasiTayade** [SensehacK/health-sense#62]
## Bug Report

Description of the iOS App bug!

### Behavior

**Current Behavior**
While switching to the dark mode the user cannot see their name on the summary page which they can in light mode.

**Expected behavior/code**
Even while accessing the application data in dark mode one can see all their information.

### Steps to Reproduce

1. Open the App
2. Navigate to Setting
3. Touch the Dark mode button and navigate back to summary screen
4. Observe the bug there should be Welcome message on the top of the screen

### Environment

- Swift version(s): 5
- OS: MacOS 10.15.3
- Xcode version: 11.4.1
- iOS: 13.4.1
- Cocoapods version(s): [e.g. v1.0.0, v1.9.1]
- Branch: Status
- Continuous Build: (Pass) - TravisCI / Github Actions
- How you are using App build: Xcode run

### Possible Solution
Switch the font color according to screen mode settings

**Additional context/Screenshots**
Add any other context about the problem here. If applicable, add screenshots to help explain.
![IMG_40670158509E-1](https://user-images.githubusercontent.com/58129928/81879811-bfc1d280-9559-11ea-884c-268a1fdc3793.jpeg)

**Comment by SensehacK** [comment]
Please test this bug on the latest patch of the app. @ManasiTayade

**Comment by ManasiTayade** [comment]
Great!! It works properly.
